Models/SignupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CJCProjectEstimatorMVC.Models
{
    public class SignupViewModel : BaseViewModel
    {
    
    }
}

Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CJCProjectEstimatorMVC.Models;


namespace CJCProjectEstimatorMVC.Controllers
{
    public class SignupController : BaseController
    {
        //
        // GET: /Signup/

        public ActionResult Thankyou()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(SignupViewModel user)
        {


            DBContext db = new DBContext();

            if (db.AppUsers.Where(a => a.UserName == user.AppUserVM.UserName).FirstOrDefault() != null)
            {
                ModelState.AddModelError("UserName", "User Name \"" + user.AppUserVM.UserName + "\" is already being used");
            }

            if (ModelState.IsValid)
            {
                AppUser appUser = new AppUser();

                appUser.FirstName = user.AppUserVM.FirstName;
                appUser.LastName = user.AppUserVM.LastName;
                appUser.UserName = user.AppUserVM.UserName;
                appUser.CompanyName = user.AppUserVM.CompanyName;
                appUser.PasswordSalt = DateTime.Now.ToString();
                appUser.PasswordHash = Hash.getHashSha256(user.AppUserVM.Password + appUser.PasswordSalt);

                
                db.AppUsers.Add(appUser);
                db.SaveChanges();

                setLoggedIn(appUser.Id);

                return Redirect("~/ProjectHome");
            }
            else
            {
                return View(user);
            }
            
        }


    }
}

Views/Signup/Index.cshtml
@model CJCProjectEstimatorMVC.Models.SignupViewModel
@{
    ViewBag.Title = "Sign-up";
}


@{ Html.EnableClientValidation(); }

   <h3><br />Sign up for the CJC Project Estimator</h3>
   <p>It's <strong>free</strong> and we won't spam you.</p>


    <div>@Html.ValidationSummary(true, "The following errors occurred while signing up:")</div>
    <div>@Html.ValidationMessageFor(model => model.AppUserVM.UserName)</div>
    <div>@Html.ValidationMessageFor(model => model.AppUserVM.FirstName)</div>
    <div>@Html.ValidationMessageFor(model => model.AppUserVM.LastName)</div>
    <div>@Html.ValidationMessageFor(model => model.AppUserVM.CompanyName)</div>
    <div>@Html.ValidationMessageFor(model => model.AppUserVM.Password)</div>
    <div>@Html.ValidationMessageFor(model => model.AppUserVM.PasswordConfirm)</div>

   
   <div class="fieldset">
    <h4 class="legend">Sign-up</h4>
    @using (Html.BeginForm("Index", "Signup"))
    {

       
        
    <table class="table">
      <tr >
        <td class="firstcoll">User Name:<span class='required'>*</span></td>
        <td>@Html.TextBoxFor(model => model.AppUserVM.UserName, new { maxlength = 40, size = 25 })

        </td>
      </tr>
      <tr >
        <td class="firstcoll">First Name:<span class='required'>*</span></td>
        <td>@Html.TextBoxFor(model => model.AppUserVM.FirstName, new { maxlength = 40, size = 25 })

        </td>
      </tr>
      <tr>
        <td class="firstcoll">Last Name:<span class='required'>*</span></td>
        <td>@Html.TextBoxFor(model => model.AppUserVM.LastName, new { maxlength = 40, size = 25 })

        </td>
      </tr>
      <tr>
        <td class="firstcoll">Company Name: </td>
        <td>@Html.TextBoxFor(model => model.AppUserVM.CompanyName, new { maxlength = 40, size = 25 })

        </td>
      </tr>
      <tr>
        <td class="firstcoll">Password:<span class='required'>*</span></td>
        <td>@Html.PasswordFor(model => model.AppUserVM.Password, new { maxlength = 15, size = 25 })

        </td>
      </tr>
      <tr>
        <td class="firstcoll">Confirm Password:<span class='required'>*</span></td>
        <td>@Html.PasswordFor(model => model.AppUserVM.PasswordConfirm, new { maxlength = 15, size = 25 })

        </td>
      </tr>
      <tr>
        <td class="firstcoll" />
        <td class="submitcoll"><input class="input" type="submit" name="Submit" id="submit" value="Submit" /></td>
      </tr>
    </table>

     
    <span class='required'>* Required Fields</span>
    <p>&nbsp;</p>

    }
    </div>

    <script type="text/javascript">
        $(".field-validation-error").addClass("error-div");
        $(".field-validation-error").parent().addClass("error-div");
        $(".validation-summary-errors").parent().addClass("error-div");
    </script>

Views/Signup/Thankyou.cshtml
@{
    ViewBag.Title = "Thank You";
}

  <div class="content">
    <h3><br>Thank you for Signing Up!</h3>

    
   <p>Welcome to CJC Project Estimator </p>
  </div>