Models/ProjectEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CJCProjectEstimatorMVC.Models
{
    public class ProjectEditViewModel : BaseViewModel
    {
        public static Dictionary<int, string> Materials { get; set; }

        public Project project { get; set; }
        public ProjectLaborItem projectLaborItem { get; set; }
        public ProjectMaterial projectMaterial { get; set; }
        
        public List<ProjectMaterialViewModel> projectMaterialViewModels { get; set; }
        public List<ProjectLaborItem> projectLaborItems { get; set; }
        public List<ProjectMaterial> projectMaterials { get; set; }

        public ProjectReportLineViewModel ProjectCosts { get; set; }

        static ProjectEditViewModel() {
            Materials = new Dictionary<int, string>();

            DBContext db = new DBContext();
            IOrderedEnumerable<Material> materialsList = (IOrderedEnumerable<Material>) db.Materials.ToList().OrderBy(x => x.Name);

            foreach (Material m in materialsList)
            {
                Materials.Add(m.MaterialId, m.Name);
            }


    
        }

    }
}

Controllers/ProjectEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CJCProjectEstimatorMVC.Models;

namespace CJCProjectEstimatorMVC.Controllers
{
    [CustomAuthorize]
    public class ProjectEditController : BaseController
    {

        private ProjectEditViewModel load(Int32? ProjectId)
        {
            ProjectEditViewModel projectEditVM = new ProjectEditViewModel();
            ProjectReportLineViewModel ProjectReportLineItem = new ProjectReportLineViewModel();
            DBContext db = new DBContext();
            Project project = new Project();
            ProjectLaborItem projectLaborItem = new ProjectLaborItem();
            ProjectMaterial projectMaterial = new ProjectMaterial();
            List<ProjectLaborItem> projectLaborItems = new List<ProjectLaborItem>();
            List<ProjectMaterial> projectMaterials = new List<ProjectMaterial>();
            List<ProjectMaterialViewModel> projectMaterialViewModels = new List<ProjectMaterialViewModel>();

            if (ProjectId != null && ProjectId > 0)
            {
                projectLaborItem.ProjectId = (Int32)ProjectId;
                projectMaterial.ProjectId = (Int32)ProjectId;
                project = db.Projects.Where(p => p.ProjectId == ProjectId).FirstOrDefault();
                projectLaborItems = db.ProjectLaborItems.Where(p => p.ProjectId == project.ProjectId).ToList<ProjectLaborItem>();
                projectMaterials = db.ProjectMaterials.Where(p => p.ProjectId == project.ProjectId).ToList<ProjectMaterial>();
                foreach (ProjectMaterial pm in projectMaterials)
                {
                    Material pmLookup = db.Materials.Where(m => m.MaterialId == pm.MaterialId).First();
                    ProjectMaterialViewModel projectMaterialViewModel = new ProjectMaterialViewModel();
                    projectMaterialViewModel.ProjectMaterialId = pm.ProjectMaterialId;
                    projectMaterialViewModel.Cost = pm.Cost;
                    projectMaterialViewModel.Number = pm.Number;
                    projectMaterialViewModel.Name = pmLookup.Name;
                    projectMaterialViewModels.Add(projectMaterialViewModel);

                }

                    
                var projectCosts = from p in db.Projects
                               join pl in db.ProjectLaborItems on p.ProjectId equals pl.ProjectId into plg
                               join pm in db.ProjectMaterials on p.ProjectId equals pm.ProjectId into pmg
                               where p.ProjectId == (int)ProjectId
                               select new
                               {
                                   Name = p.Name,
                                   CountLabor = plg.Select(a => a.ProjectId).Count(),
                                   CountMaterial = pmg.Select(a => a.ProjectId).Count(),
                                   CostMaterial = pmg.Select(a => (Double?)(a.Cost == null ? 0 : a.Cost) * (a.Number == null ? 0 : a.Number)).Sum(),
                                   CostLabor = plg.Select(a => (Double?)(a.CostPerHour == null ? 0 : a.CostPerHour) * (a.Hours == null ? 0 : a.Hours)).Sum()
                               };

                foreach (var projectCost in projectCosts)
                {

                    ProjectReportLineItem = new ProjectReportLineViewModel();
                    ProjectReportLineItem.Name = project.Name;
                    ProjectReportLineItem.QuantityOfMaterials = projectCost.CountMaterial;
                    ProjectReportLineItem.QuantityOfTasks = projectCost.CountLabor;
                    ProjectReportLineItem.TotalLaborCost = projectCost.CostLabor == null ? 0D : (Double)projectCost.CostLabor;
                    ProjectReportLineItem.TotalMaterialCost = projectCost.CostMaterial == null ? 0D : (Double)projectCost.CostMaterial;
                    ProjectReportLineItem.TotalCost = ProjectReportLineItem.TotalLaborCost + ProjectReportLineItem.TotalMaterialCost;
                    
                }
            }

            projectEditVM.project = project;
            projectEditVM.ProjectCosts = ProjectReportLineItem;
            projectEditVM.projectLaborItem = projectLaborItem;
            projectEditVM.projectMaterial = projectMaterial;
            projectEditVM.projectLaborItems = projectLaborItems;
            projectEditVM.projectMaterials = projectMaterials;
            projectEditVM.projectMaterialViewModels = projectMaterialViewModels;
            return projectEditVM;
        }


        //
        // GET: /ProjectEdit/


        [HttpGet]
        public ActionResult Index(Int32? ProjectId)
        {
            ProjectEditViewModel projectEditVM = load(ProjectId);
            return View("Index", projectEditVM);
        }


        [HttpPost]        
        public ActionResult Index(ProjectEditViewModel projectEditVM)
        {

            DBContext db = new DBContext();
             
            if (db.Projects.Where(p => p.Name == projectEditVM.project.Name).Where(p => p.ProjectId != projectEditVM.project.ProjectId).FirstOrDefault() != null)
            {
                ModelState.AddModelError("ProjectEditViewModel.project.Name", "Project Name \"" + projectEditVM.project.Name + "\" is already being used");
            }

            Project project;
            if (ModelState.IsValid)
            {
                project = new Project();
                if (projectEditVM.project.ProjectId > 0)
                {
                    project = db.Projects.First(p => p.ProjectId == projectEditVM.project.ProjectId);
                }
                else
                {
                    db.Projects.Add(project);
                }
                project.Name = projectEditVM.project.Name;
                project.AppUserId = (int)getCurrentUserId();

                db.SaveChanges();
                projectEditVM = load(project.ProjectId);
                projectEditVM.project.ProjectId = project.ProjectId;

            }
            else
            {

                projectEditVM = load(projectEditVM.project.ProjectId);
            }

            return View("Index", projectEditVM);            
        

        }

        [HttpPost] 
        public ActionResult AddProjectLaborItem(ProjectEditViewModel projectEditVM)
        {
            DBContext db = new DBContext();
            if (ModelState.IsValid)
            {

                db.ProjectLaborItems.Add(projectEditVM.projectLaborItem);
                db.SaveChanges();

            }

            projectEditVM = load(projectEditVM.projectLaborItem.ProjectId);
            return View("Index", projectEditVM);
        }

        [HttpPost] 
        public ActionResult AddProjectMaterial(ProjectEditViewModel projectEditVM)
        {
            DBContext db = new DBContext();
            if (ModelState.IsValid)
            {

                db.ProjectMaterials.Add(projectEditVM.projectMaterial);
                db.SaveChanges();

            }

            projectEditVM = load(projectEditVM.projectMaterial.ProjectId);
            return View("Index", projectEditVM);
        }


        [HttpGet]
        public ActionResult RemoveProjectLaborItem(Int32 ProjectLaborItemId)
        {
            DBContext db = new DBContext();

            ProjectLaborItem projectLaborItem = db.ProjectLaborItems.Where(p => p.ProjectLaborItemId == ProjectLaborItemId).FirstOrDefault();

            Int32? ProjectId = null;

            if (projectLaborItem != null)
            {
                ProjectId = projectLaborItem.ProjectId;
                Project project = db.Projects.Where(p => p.ProjectId == ProjectId).FirstOrDefault();
                if (project != null && project.AppUserId.Equals(getCurrentUserId()))
                {
                    db.ProjectLaborItems.Remove(projectLaborItem);
                    db.SaveChanges();
                }

            }

            ProjectEditViewModel projectEditVM = load(ProjectId);
            return View("Index", projectEditVM);
        }

        [HttpGet]
        public ActionResult RemoveProjectMaterial(Int32 ProjectMaterialId)
        {
            DBContext db = new DBContext();

            ProjectMaterial projectMaterial = db.ProjectMaterials.Where(p => p.ProjectMaterialId == ProjectMaterialId).FirstOrDefault();

            Int32? ProjectId = null;

            if (projectMaterial != null)
            {
                ProjectId = projectMaterial.ProjectId;
                Project project = db.Projects.Where(p => p.ProjectId == ProjectId).FirstOrDefault();
                if (project != null && project.AppUserId.Equals(getCurrentUserId()))
                {
                    db.ProjectMaterials.Remove(projectMaterial);
                    db.SaveChanges();
                }

            }

            ProjectEditViewModel projectEditVM = load(ProjectId);
            return View("Index", projectEditVM);
        }




        [HttpGet]
        public ActionResult RemoveProject(Int32? ProjectId)
        {
            DBContext db = new DBContext();
            
            Project project = db.Projects.Where(p => p.ProjectId == ProjectId).FirstOrDefault();

            if (project != null && project.AppUserId.Equals(getCurrentUserId()))
            {
                foreach (ProjectMaterial pm in db.ProjectMaterials.Where(p => p.ProjectId == ProjectId)) 
                {
                    db.ProjectMaterials.Remove(pm);
                }

                foreach (ProjectLaborItem pl in db.ProjectLaborItems.Where(p => p.ProjectId == ProjectId)) 
                {
                    db.ProjectLaborItems.Remove(pl);
                }

Controllers/ProjectHomeController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace CJCProjectEstimatorMVC.Controllers
{
    [CustomAuthorize]
    public class ProjectHomeController : BaseController
    {
        //
        // GET: /ProjectHome/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Views/ProjectEdit/Index.cshtml
@model CJCProjectEstimatorMVC.Models.ProjectEditViewModel
@{
    ViewBag.Title = "Project";
}
<div class="container">

<div class="content">

<h4>Estimate Management Dashboard</h4>

    @if (Model.project != null && Model.project.ProjectId > 0 )
    {
        <text>(change project name by updating and saving)</text>
    }

@using (Html.BeginForm("Index", "ProjectEdit"))
{
    <div>@Html.ValidationSummary(true, "The following errors occurred while creating a project:")</div>
    <div>@Html.ValidationMessageFor(model => model.project.Name)</div>
    <div>@Html.ValidationMessageFor(model => model.projectLaborItem.Description)</div>
    <div>@Html.ValidationMessageFor(model => model.projectLaborItem.Hours)</div>
    <div>@Html.ValidationMessageFor(model => model.projectLaborItem.CostPerHour)</div>
    <div>@Html.ValidationMessageFor(model => model.projectMaterial.Cost)</div>
    <div>@Html.ValidationMessageFor(model => model.projectMaterial.Number)</div>
    <div>@Html.ValidationMessageFor(model => model.projectMaterial.MaterialId)</div>
    <div>@Html.ValidationMessageFor(model => model.projectMaterial.ProjectId)</div>
    <div>@Html.ValidationMessageFor(model => model.projectMaterial.ProjectMaterialId)</div>
    <div>@Html.ValidationMessageFor(model => model.projectLaborItem.ProjectLaborItemId)</div>
    
    @Html.LabelFor(model => model.project.Name, "Project Name:")<span class='required'>*</span>
    @Html.TextBoxFor(model => model.project.Name, new { maxlength = 40 })
    @Html.HiddenFor(model => model.project.ProjectId)

    <input type="submit" value="Save" />
}
    
    <div class="dashboard2">
        <div class="legend">Manage Labor</div>
    

@using (Html.BeginForm("AddProjectLaborItem", "ProjectEdit"))
{
    @Html.LabelFor(model => model.projectLaborItem.Description, "Description:")<span class='required'>*</span>
    @Html.TextBoxFor(model => model.projectLaborItem.Description, new { maxlength = 50, size = 25 })    <br/>
    @Html.LabelFor(model => model.projectLaborItem.Hours, "Labor Hours:")<span class='required'>*</span> 
    @Html.TextBoxFor(model => model.projectLaborItem.Hours, new { maxlength = 7, size = 25 })    <br/>
    @Html.LabelFor(model => model.projectLaborItem.CostPerHour, "Labor Rate:")<span class='required'>*</span> 
    @Html.TextBoxFor(model => model.projectLaborItem.CostPerHour, new { maxlength = 7, size = 25 })    <br/>
    @Html.HiddenFor(model => model.projectLaborItem.ProjectId)
    @Html.HiddenFor(model => model.projectLaborItem.ProjectLaborItemId)

    <input type="submit" class="input addButton" value="Add Labor"/>
    

}
<p />

        
<div class="dashboardTable">Current Labor Line Items

<table class="projectItems">
<thead><tr>
<th>Description</th>
<th>Hours</th>
<th>Rate</th>
<th></th>
</tr>
</thead>
<tbody>
 @foreach (CJCProjectEstimatorMVC.Models.ProjectLaborItem projectLaborItem in Model.projectLaborItems)
 {
   <tr>
       <td style="text-align:left;">
       @projectLaborItem.Description
       </td>
      <td>
      @projectLaborItem.Hours
      </td>
      <td>
      @String.Format("{0:c}", projectLaborItem.CostPerHour)
      </td>
      <td>
      @Html.ActionLink("[Remove]", "RemoveProjectLaborItem", "ProjectEdit", new { ProjectLaborItemId = projectLaborItem.ProjectLaborItemId }, new { @class = "removeProject" })
      </td>
   </tr>
 }

</tbody>
</table></div>
 </div>


    <div class="dashboard2">
<div class="legend">Manage Materials</div>
@using (Html.BeginForm("AddProjectMaterial", "ProjectEdit"))
{
    @Html.LabelFor(model => model.projectMaterial.MaterialId, "Material:")<span class='required'>*</span>
    @Html.DropDownListFor(model => model.projectMaterial.MaterialId, new SelectList(CJCProjectEstimatorMVC.Models.ProjectEditViewModel.Materials, "Key", "Value"))
<br/>
    
    @Html.LabelFor(model => model.projectMaterial.Cost, "Material Cost:")<span class='required'>*</span>
    @Html.TextBoxFor(model => model.projectMaterial.Cost, new { maxlength = 7, size = 25 })    <br/>
    @Html.LabelFor(model => model.projectMaterial.Number, "Material Quantity:")<span class='required'>*</span>
    @Html.TextBoxFor(model => model.projectMaterial.Number, new { maxlength = 7, size = 25 })  <br/>  
    @Html.HiddenFor(model => model.projectMaterial.ProjectId)
    @Html.HiddenFor(model => model.projectMaterial.ProjectMaterialId)
    <input type="submit" class="input addButton" value="Add Material" />
}

        <div class="dashboardTable">Current Materials

<table class="projectItems">
<thead><tr>
<th>Name</th>
<th>Number</th>
<th>Cost</th>
<th></th>
</tr>
</thead>
<tbody>
 @foreach (CJCProjectEstimatorMVC.Models.ProjectMaterialViewModel projectMaterialViewModel in Model.projectMaterialViewModels)
 {
   <tr>
       <td style="text-align:left;">
       @projectMaterialViewModel.Name
       </td>
       <td>
       @projectMaterialViewModel.Number
       </td>
       <td>
       @String.Format("{0:c}", projectMaterialViewModel.Cost)
       </td>
      <td>

      @Html.ActionLink("[Remove]", "RemoveProjectMaterial", "ProjectEdit", new { ProjectMaterialId = projectMaterialViewModel.ProjectMaterialId }, new { @class = "removeProject" })

      </td>
   </tr>
 }

</tbody>
</table></div>
</div> 
<div class="dashboardCosts">
<div class="legend">Project Totals</div>

<div class="dashboardTable"><table class="projectItems">
<tr><td>Total Labor:</td><td class='numberColumn'> @String.Format("{0:c}", Model.ProjectCosts.TotalLaborCost)</td></tr>
<tr><td>Total Materials:</td><td class='numberColumn'> @String.Format("{0:c}", Model.ProjectCosts.TotalMaterialCost)</td></tr>
<tr><td>Grand Total:</td><td class='numberColumn'> @String.Format("{0:c}", Model.ProjectCosts.TotalCost)</td></tr>

</table>
</div></div>



<div class="contentClear"><p>Return to the @Html.ActionLink("Projects Page", "Index", "ProjectHome")</p></div>
</div>
</div>







 <script>
     $(document).ready(function () {
         $('.removeProject').click(function () {
             if (confirm("Are you sure you want to delete this?")) {
                 return true;
             }
             return false;
         });

     
    
     @if (Model.project == null || Model.project.ProjectId < 1)
     {
         <text>
         $('.addButton').click(function () {
             alert("Please save a new project before adding labor or materials.");
             return false;
         });
         </text>
     }


     });
</script>